version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build: .
    command: sh -c '/wait-for-it.sh -t 0 db:3306 -- python /src/manage.py makemigrations && python /src/manage.py migrate && python /src/manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - db